[pytest]
testpaths = tests
norecursedirs = outputs temp test_reports backup .git .pytest_cache __pycache__
filterwarnings =
    ignore::pytest.PytestReturnNotNoneWarning
    ignore::FutureWarning
    ignore::DeprecationWarning:.*swig.*
