from __future__ import annotations

from dataclasses import dataclass

from API.config import (
    REPORT_TEMPLATE_AUTHOR,
    REPORT_TEMPLATE_FOOTER,
    REPORT_TEMPLATE_LOGO,
    REPORT_TEMPLATE_SUBTITLE,
    REPORT_TEMPLATE_TITLE,
    REPORT_TEMPLATE_TOC,
    REPORT_FONT_EN,
    REPORT_FONT_ZH,
)


@dataclass
class ReportTemplate:
    title: str = "DeepAnalyze 报告"
    subtitle: str = "自动化数据分析"
    author: str = "DeepAnalyze"
    include_toc: bool = True
    logo_url: str | None = None
    footer: str = "Generated by DeepAnalyze"
    font_family: str = "'Noto Sans', Arial, sans-serif"


DEFAULT_TEMPLATE = ReportTemplate()


def template_from_config(language: str | None = None) -> ReportTemplate:
    font_family = REPORT_FONT_ZH if language == "zh" else REPORT_FONT_EN
    return ReportTemplate(
        title=REPORT_TEMPLATE_TITLE,
        subtitle=REPORT_TEMPLATE_SUBTITLE,
        author=REPORT_TEMPLATE_AUTHOR,
        include_toc=REPORT_TEMPLATE_TOC,
        logo_url=REPORT_TEMPLATE_LOGO or None,
        footer=REPORT_TEMPLATE_FOOTER,
        font_family=font_family,
    )
