"""
Configuration module for DeepAnalyze API Server
Contains all configuration constants and environment setup
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Environment setup
os.environ.setdefault("MPLBACKEND", "Agg")

def _load_env_file() -> None:
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file()

def _get_int_env(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _get_bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# API Configuration (LLM backend)
API_BASE = os.getenv("DEEPANALYZE_VLLM_BASE_URL", "http://localhost:48000/v1")
VLLM_BASE_URL = API_BASE
VLLM_BASE_URL_NO_V1 = API_BASE[:-3] if API_BASE.endswith("/v1") else API_BASE
DEEPANALYZE_VLLM_API_KEY = os.getenv("DEEPANALYZE_VLLM_API_KEY", "")
MODEL_PATH = os.getenv("DEEPANALYZE_MODEL_PATH", "default")
DEEPANALYZE_VLLM_API_KEY = os.getenv("DEEPANALYZE_VLLM_API_KEY", "<Enter-Your-API-Key>")


# Workspace and file server
WORKSPACE_BASE_DIR = os.getenv("DEEPANALYZE_WORKSPACE_DIR", "workspace")
FILE_SERVER_HOST = os.getenv("DEEPANALYZE_FILE_SERVER_HOST", "localhost")
HTTP_SERVER_PORT = _get_int_env("DEEPANALYZE_FILE_SERVER_PORT", 48100)
HTTP_SERVER_BASE = f"http://{FILE_SERVER_HOST}:{HTTP_SERVER_PORT}"

# API Server Configuration
API_HOST = os.getenv("DEEPANALYZE_API_HOST", "0.0.0.0")
API_PORT = _get_int_env("DEEPANALYZE_API_PORT", _get_int_env("API_PORT", 48200))
API_PUBLIC_HOST = os.getenv("DEEPANALYZE_API_PUBLIC_HOST", "localhost")
API_PUBLIC_BASE = f"http://{API_PUBLIC_HOST}:{API_PORT}"
API_PUBLIC_BASE_V1 = f"{API_PUBLIC_BASE}/v1"
API_TITLE = "DeepAnalyze OpenAI-Compatible API"
API_VERSION = "1.0.0"

# Thread cleanup configuration
CLEANUP_TIMEOUT_HOURS = 12
CLEANUP_INTERVAL_MINUTES = 30

# Code execution configuration
CODE_EXECUTION_TIMEOUT = 120
MAX_NEW_TOKENS = 32768
EXECUTION_MAX_RETRIES = _get_int_env("DEEPANALYZE_EXECUTION_MAX_RETRIES", 2)
CODEGEN_CONCURRENCY = _get_int_env("DEEPANALYZE_CODEGEN_CONCURRENCY", 2)
EXECUTION_CONCURRENCY = _get_int_env("DEEPANALYZE_EXECUTION_CONCURRENCY", 1)
ALLOW_ABSOLUTE_IO = _get_bool_env("DEEPANALYZE_ALLOW_ABSOLUTE_IO", False)

# File handling configuration
FILE_STORAGE_DIR = os.path.join(WORKSPACE_BASE_DIR, "_files")
VALID_FILE_PURPOSES = ["answers", "file-extract", "assistants"]

# Model configuration
DEFAULT_TEMPERATURE = 0.4
DEFAULT_MODEL = os.getenv("DEEPANALYZE_DEFAULT_MODEL", os.getenv("DEFAULT_MODEL", "default"))

# Stop token IDs for the configured model (optional)
STOP_TOKEN_IDS = []

# Supported tools
SUPPORTED_TOOLS = ["code_interpreter"]

# Demo/Frontend settings
FRONTEND_HOST = os.getenv("DEEPANALYZE_FRONTEND_HOST", "localhost")
FRONTEND_PORT = _get_int_env("DEEPANALYZE_FRONTEND_PORT", 4000)
FRONTEND_BASE = f"http://{FRONTEND_HOST}:{FRONTEND_PORT}"

WEBSOCKET_HOST = os.getenv("DEEPANALYZE_WEBSOCKET_HOST", "localhost")
WEBSOCKET_PORT = _get_int_env("DEEPANALYZE_WEBSOCKET_PORT", 8001)
WEBSOCKET_URL = f"ws://{WEBSOCKET_HOST}:{WEBSOCKET_PORT}"

# Jupyter demo settings
JUPYTER_PORT = _get_int_env("DEEPANALYZE_JUPYTER_PORT", 8888)

# Orchestration settings
USE_ORCHESTRATOR = _get_bool_env("DEEPANALYZE_USE_ORCHESTRATOR", False)
MAX_RECURSION_DEPTH = _get_int_env("DEEPANALYZE_MAX_DEPTH", 1)
if MAX_RECURSION_DEPTH < 0:
    MAX_RECURSION_DEPTH = 0
if MAX_RECURSION_DEPTH > 3:
    MAX_RECURSION_DEPTH = 3

REPORT_FORMAT = os.getenv("DEEPANALYZE_REPORT_FORMAT", "html")
REPORT_LANGUAGE = os.getenv("DEEPANALYZE_REPORT_LANGUAGE", "zh")
REPORT_EXPORT_MODE = os.getenv("DEEPANALYZE_REPORT_EXPORT_MODE", "html_convert")
REPORT_TEMPLATE_TITLE = os.getenv("DEEPANALYZE_REPORT_TITLE", "DeepAnalyze 报告")
REPORT_TEMPLATE_SUBTITLE = os.getenv(
    "DEEPANALYZE_REPORT_SUBTITLE", "自动化数据分析"
)
REPORT_TEMPLATE_AUTHOR = os.getenv("DEEPANALYZE_REPORT_AUTHOR", "DeepAnalyze")
REPORT_TEMPLATE_LOGO = os.getenv("DEEPANALYZE_REPORT_LOGO", "")
REPORT_TEMPLATE_TOC = _get_bool_env("DEEPANALYZE_REPORT_TOC", True)
REPORT_TEMPLATE_FOOTER = os.getenv(
    "DEEPANALYZE_REPORT_FOOTER", "Generated by DeepAnalyze"
)
REPORT_FONT_ZH = os.getenv("DEEPANALYZE_REPORT_FONT_ZH", "'Noto Sans CJK SC', 'PingFang SC', 'Microsoft YaHei', sans-serif")
REPORT_FONT_EN = os.getenv("DEEPANALYZE_REPORT_FONT_EN", "'Noto Sans', 'Helvetica Neue', Arial, sans-serif")
PROMPT_SET = os.getenv("DEEPANALYZE_PROMPT_SET", "default")

GRAPH_MONITORING = _get_bool_env("DEEPANALYZE_GRAPH_MONITORING", False)
TRACE_ENABLED = _get_bool_env("DEEPANALYZE_TRACE_ENABLED", True)
DATA_QUALITY_ENABLED = _get_bool_env("DEEPANALYZE_DATA_QUALITY_ENABLED", True)
REPRO_METADATA_ENABLED = _get_bool_env("DEEPANALYZE_REPRO_METADATA_ENABLED", True)

# Visualization settings
VISUAL_STYLE = os.getenv("DEEPANALYZE_VISUAL_STYLE", "academic")
VISUAL_INTERACTIVE = _get_bool_env("DEEPANALYZE_VISUAL_INTERACTIVE", False)


def get_vllm_port() -> int | None:
    parsed = urlparse(API_BASE)
    if parsed.port:
        return parsed.port
    if parsed.scheme == "https":
        return 443
    if parsed.scheme == "http":
        return 80
    return None
